### PR TITLE
Onboarding, Register, Login, Profile Creation, Map Views

### LINKED ISSUE #39: Create Map View
We need a map view that has a full map at the top with a heading and a call to action button that will take the user to the event list view.

image

### LINKED ISSUE #40: Create refined login/register view

### LINKED ISSUE #41: Create onboarding view

### LINKED ISSUE #42: Create profile creation form view

### PR DESCRIPTION
**Pull request by JustinASmith**
Resolves #39 
Resolves #40 
Resolves #41 
Resolves #42

### CODE REVIEW

**Review by NathanCheshire — APPROVED** [review]
Looks good! I'll DM you about widgets and how I can incorporate them into the ELV if I encounter issues.

**Comment by JustinASmith** [comment]
I've made a bit of progress on this, but I am still unsure how to make this perfect. The issue I have had deals with multiple rebuilds of the UI and/or the UI not displaying the correct screen due to state of user auth and user profile creation.

Things I have tried:
- Creating a Dart Stream from a Future and combining that with the onAuthStateChanged Stream from Firebase. The Future in this case is a network request to the Firebase Firestore "user_profiles" database collection to see if the user has a profile created.
- I have also tried adding a post frame callback to the Wrapper widget that calls the same API to check if the user has a profile and redirects them to the Profile Creation if they don't. This was not successful because the user would log in and be sent to the Map view, then the post frame callback would make a network request to see if they had a profile and if they didn't it would redirect them. This isn't ideal because the wrong screen is displayed for some time. Instead it needs to be a loading screen or something like that. The reason I can't just show a loading widget until the post frame callback completes is due to the nature and reasoning behind the Wrapper component. The Wrapper is to determine the authentication state of the user, which is needed for everything in the app and simply showing a spinner and always checking if they user has a profile on each navigation change is not idea. The post frame callback would do that. Every navigation it would be called. 
- What I am trying now is hoisting the onAuthStateChange stream outside of the Material app so that there can be another stream for checking that the user has a profile. This is a work in progress, but it is starting to make a little sense. I am using this https://github.com/bizz84/firebase_auth_demo_flutter/issues/32 resource for help. The underlying repo on this issue has shown to be helpful so far. I will continue with this unless this proves to be a dead end as well.

**Comment by JustinASmith** [comment]
This wasn't necessarily ready to merge... I will try to get the fix code and have a separate PR for that.

**Comment by JustinASmith** [comment]
I would like to point out, I made mistakes with this PR. I did not incrementally add screens or features. I bundled many things into one branch/PR and this is something that I should have broken out further. The issue I am still currently fixing is likely a result of this and a lack of understanding of Streams and the overall lifecycle of a Flutter Material app. Going forward, I will keep these mistakes in mind.

**Pull request merged**
